const mongoose = require('mongoose')
const Schema = mongoose.Schema
const MODELS = require('../constants/model-names')

const LOCALIZATION_KEYS = ["ONBOARDING_TITLE_ONE", "ONBOARDING_TITLE_TWO", "ONBOARDING_TITLE_THREE", "GO_BACK", "NEXT", "REGISTER", "REGISTER_PAGE_DESCRIPTION", "PHONE", "OTP_INPUT_DESCRIPTION", "OTP_ENTER_BUTTON_TEXT", "INVALID_PHONE_NUMBER_ERROR", "CHECK_YOUR_INTERNET", "ENTER_FULL_NAME", "ENTER_EMAIL_ADDRESS", "EMAIL_IS_OPTIONAL", "NAME_CANT_BE_EMPTY", "INVALID_EMAIL_ADDRESS", "GENDER", "MALE", "FEMALE", "SELECT_YOUR_GENDER", "WHERE_DO_YOU_WANT_TO_GO", "PLEASE_TRY_AGAIN", "YOUR_PICKUP_ADDRESS", "PERSON", "BIRR_PER_KM", "BIRR", "WITH_CASH", "CORPORATE_PAYMENT", "CREATE_SCHEDULE", "BID", "NOTE_FOR_YOUR_RIDE", "ESTIMATION", "FINISH", "WRITE_HERE", "PAYMENT", "MINUTE", "KM", "OK", "TRY_AGAIN", "NO_DRIVERS_FOUND_AROUND_YOU", "SEARCHING_FOR_DRIVERS", "CANCEL_TRIP_REQUEST", "VEHICLE_TYPE", "ARRIVES_IN", "TRIP_COMPLETED", "KM_TRIP", "DRIVER", "THE_VEHICLE", "HOW_WAS_YOUR_TRIP", "DRIVER_ARRIVED", "TRIP_STARTED", "TRIP_IS_CANCELLED", "ILIFT_MILES", "MESSAGE_FROM_ILIFT", "TRIP_HISTORY", "SCHEDULE_TRIPS", "PROFILE", "INVITE_TO_ILIFT", "YOUR_ILIFT_MILES", "CONVERT_TO_MOBILE_CARD", "CARD_HISTORY", "SCHEDULED_TO", "FROM", "TO", "CANCEL_SCHEDULE", "YES", "NO", "ARE_YOU_Sure", "ENTER_BID_AMOUNT", "INVALID_AMOUNT", "AMOUNT_HAS_TO_BE_GREATED", "BID_AMOUNT", "ENTER_TICKET", "INVALID_TICKET", "TEMPORARILY_LOCKED_TICKET", "SCHEDULED", "COMPLETED", "CANCELLED", "UPLOAD_YOUR_PIC", "TO_EDIT_YOUR_PROFILE", "CHANGE_LANGUAGE", "SIGN_OUT", "INVALID_NAME", "LOCATION_PERMISSION_DENIED", "LOCATION_PERMISSION_DENIED_PERMANENTLY", "ALLOW_LOCATION_PERMISSION_FROM_SETTINGS", "ASK_LOCATION_PERMISSION", "CANCEL_TRIP", "THERE_ARE_NO_ITEMS", "MOBILE_CARD", "VOUCHER_HISTORY", "FINDING_PLACE", "NO_RESULT_FOUND", "SEARCH_LOCATION", "ADD_FAV_PLACE", "FAVORITE_PLACE_NAME", "FAVORITE_PLACE_NAME_HINT", "DOUBLE_TAP_TO_DELETE_FAV_PLACE", "NEW_VERSION_AVAILABLE", "OPTIONAL_UPDATE_SUBTITLE", "FORCE_UPDATE_SUBTITLE", "SKIP", "UPDATE"]

const PassengerLocalizationSchema = Schema({
    name: String,
    data: Object.fromEntries(LOCALIZATION_KEYS.map(key => [key, { type: 'string', required: true }]))
},
    {
        timestamps: true
    })


PassengerLocalizationSchema.index(
    { name: 1 },
    {
        unique: true,
    }
)

module.exports = mongoose.model(MODELS.PASSENGER_LOCALIZATIONS, PassengerLocalizationSchema)